services:
  db:
    image: postgres:18
    container_name: esencap_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: esencap_database
      POSTGRES_USER: esencap_user
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esencap_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
